// react-ts/src/App.tsx
import { Sorting } from "./Sorting";

function App() {
  return (
    <>
      <Sorting />

      <Sorting sorting="asc" />

      <Sorting direction="asc" />

      <Sorting direction="asc1" />

      <Sorting sorting={"asc"} />

      <Sorting direction={"asc"} />

      <Sorting direction={"asc1"} />

      <Soritng />
    </>
  );
}

export default App;

// angular-ts/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SortingComponent } from './sorting.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, SortingComponent],
  template: `
    <sorting />
    <sorting sorting="asc" />
    <sorting [sorting]="'asc'" />
    <sorting direction="asc" />
    <sorting [direction]="'asc'" />
    <sorting direction="asc1" />
    <sorting [direction]="'asc1'" />
    <soritng />
  `,
})
export class AppComponent {
  title = 'angular-ts';
}
