// react-ts/src/App.tsx
import { Sorting } from "./Sorting";

function App() {
  return (
    <>
      <Sorting />

      <Sorting sorting="asc" />

      <Sorting direction="asc" />

      <Sorting direction="asc1" />

      <Sorting sorting={"asc"} />

      <Sorting direction={"asc"} />

      <Sorting direction={"asc1"} />

      <Soritng />
    </>
  );
}

export default App;

// vue-ts/src/App.vue
<script setup lang="ts">
import Sorting from "./components/Sorting.vue";
</script>

<template>
  <Sorting />
  <Sorting sorting="asc" />
  <Sorting direction="asc" />
  <Sorting direction="asc1" />
  <Sorting :sorting="'asc'" />
  <Sorting :direction="'asc'" />
  <Sorting :direction="'asc1'" />
  <Soritng />
</template>
